# Use Secondary_ID to specify master id and name the slave with "_slave" at the end
# to ignore it in controller creation.

palbator_arm_shoulder_1_joint:
  ID: 2
  Secondary_ID: 255
  Return_Delay_Time: 0
  Operating_Mode: 3 # Position Control Mode
  Homing_Offset: -120
  Min_Position_Limit: 1240
  Max_Position_Limit: 2860
  Profile_Acceleration: 0
  Profile_Velocity: 0

palbator_arm_shoulder_2_joint:
  ID: 3
  Secondary_ID: 255
  Return_Delay_Time: 0
  Operating_Mode: 3 # Position Control Mode
  Homing_Offset: -322
  Min_Position_Limit: 512
  Max_Position_Limit: 3583
  Profile_Acceleration: 0
  Profile_Velocity: 0
 
palbator_arm_shoulder_3_joint:
  ID: 4
  Secondary_ID: 255
  Return_Delay_Time: 0
  Operating_Mode: 3 # Position Control Mode
  Homing_Offset: -42
  Min_Position_Limit: 1024
  Max_Position_Limit: 2758
  Profile_Acceleration: 0
  Profile_Velocity: 0

palbator_arm_shoulder_3_joint_slave:
  ID: 5
  Secondary_ID: 4
  Drive_Mode: 1
  Return_Delay_Time: 0
  Operating_Mode: 3 # Position Control Mode
  Homing_Offset: 44
  Min_Position_Limit: 1024
  Max_Position_Limit: 2758
  Profile_Acceleration: 0
  Profile_Velocity: 0

palbator_arm_wrist_1_joint:
  ID: 6
  Secondary_ID: 255
  Return_Delay_Time: 0
  Operating_Mode: 3 # Position Control Mode
  Homing_Offset: 0
  Min_Position_Limit: 0
  Max_Position_Limit: 4095
  Profile_Acceleration: 0
  Profile_Velocity: 0

palbator_arm_wrist_2_joint:
  ID: 7
  Secondary_ID: 255
  Return_Delay_Time: 0
  Operating_Mode: 3 # Position Control Mode
  Homing_Offset: 0
  Min_Position_Limit: 1024
  Max_Position_Limit: 3071
  Profile_Acceleration: 0
  Profile_Velocity: 0

palbator_arm_wrist_3_joint:
  ID: 8
  Secondary_ID: 255
  Return_Delay_Time: 0
  Operating_Mode: 3 # Position Control Mode
  Homing_Offset: 248
  Min_Position_Limit: 0
  Max_Position_Limit: 4095
  Profile_Acceleration: 0
  Profile_Velocity: 0

motor1_hand_joint:
  ID: 10
  Secondary_ID: 255
  Return_Delay_Time: 0
  Operating_Mode: 3 # Position Control Mode
  PWM_Limit: 300    # limit torque
  Homing_Offset: 0
  Min_Position_Limit: 1297
  Max_Position_Limit: 2330
  Profile_Acceleration: 0
  Profile_Velocity: 0

motor2_hand_joint:
  ID: 11
  Secondary_ID: 255
  # Secondary_ID: 10
  # Drive_Mode: 1
  Return_Delay_Time: 0
  Operating_Mode: 3 # Position Control Mode
  PWM_Limit: 300    # limit torque
  Homing_Offset: 0
  Min_Position_Limit: 1297
  Max_Position_Limit: 2330
  Profile_Acceleration: 0
  Profile_Velocity: 0
  