palbator_arm_shoulder_3_joint_slave:
  ID: 5
  Secondary_ID: 4
  Drive_Mode: 1
  Return_Delay_Time: 0
  Operating_Mode: 3 # Position Control Mode
  Homing_Offset: -42
  Min_Position_Limit: 1024
  Max_Position_Limit: 2758
  Profile_Acceleration: 0
  Profile_Velocity: 0